In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
#raw_data = pd.read_csv("C:/Users/Elias/Documents/DSTI/ML with Python Project/books.csv",index_col="bookId")
#raw_data = pd.read_csv("C:/Users/Elias/Documents/DSTI/ML with Python Project/books.csv",on_bad_lines='skip')
raw_data = pd.read_csv("C:/Users/Elias/Documents/DSTI/ML with Python Project/books.csv",on_bad_lines='warn')

In [31]:
raw_data

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9.780440e+12,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9.780440e+12,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9.780440e+12,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9.780440e+12,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9.780440e+12,eng,2690,41428,164,9/13/2004,Scholastic
...,...,...,...,...,...,...,...,...,...,...,...,...
11122,45631,Expelled from Eden: A William T. Vollmann Reader,William T. Vollmann/Larry McCaffery/Michael He...,4.06,1560254416,9.781560e+12,eng,512,156,20,12/21/2004,Da Capo Press
11123,45633,You Bright and Risen Angels,William T. Vollmann,4.08,0140110879,9.780140e+12,eng,635,783,56,12/1/1988,Penguin Books
11124,45634,The Ice-Shirt (Seven Dreams #1),William T. Vollmann,3.96,0140131965,9.780140e+12,eng,415,820,95,8/1/1993,Penguin Books
11125,45639,Poor People,William T. Vollmann,3.72,0060878827,9.780060e+12,eng,434,769,139,2/27/2007,Ecco
11126,45641,Las aventuras de Tom Sawyer,Mark Twain,3.91,8497646983,9.788500e+12,spa,272,113,12,5/28/2006,Edimat Libros

In [24]:
col = raw_data["bookID"]

print("Missing values:", col.isna().sum())
print("Duplicate values:", col.duplicated().sum())
print("Unique values:", col.nunique())
print("Total rows:", len(col))
print("Integer dtype:", pd.api.types.is_integer_dtype(col))

Missing values: 0
Duplicate values: 0
Unique values: 11127
Total rows: 11127
Integer dtype: True

In [58]:
col = raw_data["title"]

print("Missing values:", col.isnull().sum())
print("Duplicate titles:", col.duplicated().sum())

Missing values: 0
Duplicate titles: 775

In [38]:
raw_data.loc[:,"Title Length"]=col.str.len() #add new column with title lengths

In [55]:
col = raw_data["Title Length"]
print("Minimum title length: ", min(col))
print("Maximum title length: ", max(col))

Minimum title length:  2
Maximum title length:  254

In [75]:
result = raw_data[raw_data["Title Length"] == 2]
result

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,Title Length
174,410,V.,Thomas Pynchon,3.96,0060930217,9.780060e+12,eng,547,1415,177,7/5/2005,Harper Perennial Modern Classics,2
1664,5809,V.,Thomas Pynchon/Carlos Martín Ramírez,3.96,2020418770,9.782020e+12,fre,640,15174,561,1/2/2001,Contemporary French Fiction,2
8528,32760,V.,Thomas Pynchon,3.96,3499137305,9.783500e+12,ger,544,46,4,8/1/1994,Rowohlt,2

In [63]:
groups = raw_data.groupby("title")

In [88]:
clusters = raw_data[raw_data["title"].map((raw_data["title"].value_counts() == 9) & (raw_data["title"]=="The Iliad") )]

In [79]:
raw_data["title"].value_counts()

title
The Brothers Karamazov                                  9
The Iliad                                               9
'Salem's Lot                                            8
The Odyssey                                             8
Gulliver's Travels                                      8
                                                       ..
The Noonday Demon: An Atlas of Depression               1
The Noonday Demon: An Anatomy of Depression             1
My Secret: A PostSecret Book                            1
The Secret Lives of Men and Women: A PostSecret Book    1
Las aventuras de Tom Sawyer                             1
Name: count, Length: 10352, dtype: int64

In [89]:
clusters

Empty DataFrame
Columns: [bookID, title, authors, average_rating, isbn, isbn13, language_code,   num_pages, ratings_count, text_reviews_count, publication_date, publisher, Title Length]
Index: []

In [83]:
raw_data["title"].value_counts() == 9

title
The Brothers Karamazov                                   True
The Iliad                                                True
'Salem's Lot                                            False
The Odyssey                                             False
Gulliver's Travels                                      False
                                                        ...
The Noonday Demon: An Atlas of Depression               False
The Noonday Demon: An Anatomy of Depression             False
My Secret: A PostSecret Book                            False
The Secret Lives of Men and Women: A PostSecret Book    False
Las aventuras de Tom Sawyer                             False
Name: count, Length: 10352, dtype: bool

In [90]:
raw_data["title"]=="The Iliad"

0        False
1        False
2        False
3        False
4        False
         ...
11122    False
11123    False
11124    False
11125    False
11126    False
Name: title, Length: 11127, dtype: bool